# Generated by Django 2.1 on 2018-08-03 23:25

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=50, verbose_name='عنوان')),
                ('description', tinymce.models.HTMLField(blank=True, default='', max_length=100, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='images/slider', verbose_name='تصویر')),
                ('url', models.URLField(verbose_name='لینک')),
                ('order', models.PositiveIntegerField(default=0, help_text='اسلایدها بر اساس این شماره مرتب می شوند (کوچک ترین به بزرگترین)', verbose_name='شماره')),
                ('active', models.BooleanField(default=False, help_text='اسلاید فعال در ابتدا نمایش داده می شود', verbose_name='فعال')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
