# Generated by Django 2.2.3 on 2019-08-29 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_feed_feedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedFile',
            new_name='PostFile',
        ),
        migrations.AlterField(
            model_name='postfile',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Post'),
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
