# Generated by Django 2.2.3 on 2019-08-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_post_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('jo', 'مجله'), ('pa', 'مقاله'), ('ne', 'اخبار'), ('pr', 'نرم افزار')], default='pa', max_length=2),
        ),
    ]
